package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExaminationHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationHiveAllPropertiesEquals(ExaminationHive expected, ExaminationHive actual) {
        assertExaminationHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertExaminationHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationHiveAllUpdatablePropertiesEquals(ExaminationHive expected, ExaminationHive actual) {
        assertExaminationHiveUpdatableFieldsEquals(expected, actual);
        assertExaminationHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationHiveAutoGeneratedPropertiesEquals(ExaminationHive expected, ExaminationHive actual) {
        assertThat(expected)
            .as("Verify ExaminationHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationHiveUpdatableFieldsEquals(ExaminationHive expected, ExaminationHive actual) {
        assertThat(expected)
            .as("Verify ExaminationHive relevant properties")
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getDateExamination()).as("check dateExamination").isEqualTo(actual.getDateExamination()))
            .satisfies(e -> assertThat(e.getReminderId()).as("check reminderId").isEqualTo(actual.getReminderId()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExaminationHiveUpdatableRelationshipsEquals(ExaminationHive expected, ExaminationHive actual) {
        assertThat(expected)
            .as("Verify ExaminationHive relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()));
    }
}
