package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedingHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedingHiveAllPropertiesEquals(FeedingHive expected, FeedingHive actual) {
        assertFeedingHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedingHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedingHiveAllUpdatablePropertiesEquals(FeedingHive expected, FeedingHive actual) {
        assertFeedingHiveUpdatableFieldsEquals(expected, actual);
        assertFeedingHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedingHiveAutoGeneratedPropertiesEquals(FeedingHive expected, FeedingHive actual) {
        assertThat(expected)
            .as("Verify FeedingHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedingHiveUpdatableFieldsEquals(FeedingHive expected, FeedingHive actual) {
        assertThat(expected)
            .as("Verify FeedingHive relevant properties")
            .satisfies(e -> assertThat(e.getFoodAmount()).as("check foodAmount").isEqualTo(actual.getFoodAmount()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()))
            .satisfies(e -> assertThat(e.getDateFinished()).as("check dateFinished").isEqualTo(actual.getDateFinished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedingHiveUpdatableRelationshipsEquals(FeedingHive expected, FeedingHive actual) {
        assertThat(expected)
            .as("Verify FeedingHive relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()));
    }
}
