package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GoodHarvestHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGoodHarvestHiveAllPropertiesEquals(GoodHarvestHive expected, GoodHarvestHive actual) {
        assertGoodHarvestHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertGoodHarvestHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGoodHarvestHiveAllUpdatablePropertiesEquals(GoodHarvestHive expected, GoodHarvestHive actual) {
        assertGoodHarvestHiveUpdatableFieldsEquals(expected, actual);
        assertGoodHarvestHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGoodHarvestHiveAutoGeneratedPropertiesEquals(GoodHarvestHive expected, GoodHarvestHive actual) {
        assertThat(expected)
            .as("Verify GoodHarvestHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGoodHarvestHiveUpdatableFieldsEquals(GoodHarvestHive expected, GoodHarvestHive actual) {
        assertThat(expected)
            .as("Verify GoodHarvestHive relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGoodHarvestHiveUpdatableRelationshipsEquals(GoodHarvestHive expected, GoodHarvestHive actual) {
        assertThat(expected)
            .as("Verify GoodHarvestHive relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()))
            .satisfies(e -> assertThat(e.getHarvestType()).as("check harvestType").isEqualTo(actual.getHarvestType()));
    }
}
