package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllPropertiesEquals(Group expected, Group actual) {
        assertGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllUpdatablePropertiesEquals(Group expected, Group actual) {
        assertGroupUpdatableFieldsEquals(expected, actual);
        assertGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAutoGeneratedPropertiesEquals(Group expected, Group actual) {
        assertThat(expected)
            .as("Verify Group auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableFieldsEquals(Group expected, Group actual) {
        assertThat(expected)
            .as("Verify Group relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getEnumValueName()).as("check enumValueName").isEqualTo(actual.getEnumValueName()))
            .satisfies(e -> assertThat(e.getColor()).as("check color").isEqualTo(actual.getColor()))
            .satisfies(e -> assertThat(e.getHiveCount()).as("check hiveCount").isEqualTo(actual.getHiveCount()))
            .satisfies(e -> assertThat(e.getHiveCountFinished()).as("check hiveCountFinished").isEqualTo(actual.getHiveCountFinished()))
            .satisfies(e -> assertThat(e.getAdditionalInfo()).as("check additionalInfo").isEqualTo(actual.getAdditionalInfo()))
            .satisfies(e -> assertThat(e.getOrderNumber()).as("check orderNumber").isEqualTo(actual.getOrderNumber()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableRelationshipsEquals(Group expected, Group actual) {
        // empty method
    }
}
