package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HarvestTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestTypeAllPropertiesEquals(HarvestType expected, HarvestType actual) {
        assertHarvestTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertHarvestTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestTypeAllUpdatablePropertiesEquals(HarvestType expected, HarvestType actual) {
        assertHarvestTypeUpdatableFieldsEquals(expected, actual);
        assertHarvestTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestTypeAutoGeneratedPropertiesEquals(HarvestType expected, HarvestType actual) {
        assertThat(expected)
            .as("Verify HarvestType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestTypeUpdatableFieldsEquals(HarvestType expected, HarvestType actual) {
        assertThat(expected)
            .as("Verify HarvestType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestTypeUpdatableRelationshipsEquals(HarvestType expected, HarvestType actual) {
        // empty method
    }
}
