package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HarvestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestAllPropertiesEquals(Harvest expected, Harvest actual) {
        assertHarvestAutoGeneratedPropertiesEquals(expected, actual);
        assertHarvestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestAllUpdatablePropertiesEquals(Harvest expected, Harvest actual) {
        assertHarvestUpdatableFieldsEquals(expected, actual);
        assertHarvestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestAutoGeneratedPropertiesEquals(Harvest expected, Harvest actual) {
        assertThat(expected)
            .as("Verify Harvest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestUpdatableFieldsEquals(Harvest expected, Harvest actual) {
        assertThat(expected)
            .as("Verify Harvest relevant properties")
            .satisfies(e -> assertThat(e.getHiveFrames()).as("check hiveFrames").isEqualTo(actual.getHiveFrames()))
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getDateCollected()).as("check dateCollected").isEqualTo(actual.getDateCollected()))
            .satisfies(e -> assertThat(e.getGroup()).as("check group").isEqualTo(actual.getGroup()))
            .satisfies(e -> assertThat(e.getGroupRecordId()).as("check groupRecordId").isEqualTo(actual.getGroupRecordId()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestUpdatableRelationshipsEquals(Harvest expected, Harvest actual) {
        assertThat(expected)
            .as("Verify Harvest relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()))
            .satisfies(e -> assertThat(e.getHarvestType()).as("check harvestType").isEqualTo(actual.getHarvestType()));
    }
}
