package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveAllPropertiesEquals(Hive expected, Hive actual) {
        assertHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveAllUpdatablePropertiesEquals(Hive expected, Hive actual) {
        assertHiveUpdatableFieldsEquals(expected, actual);
        assertHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveAutoGeneratedPropertiesEquals(Hive expected, Hive actual) {
        assertThat(expected)
            .as("Verify Hive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveUpdatableFieldsEquals(Hive expected, Hive actual) {
        assertThat(expected)
            .as("Verify Hive relevant properties")
            .satisfies(e -> assertThat(e.getBarcode()).as("check barcode").isEqualTo(actual.getBarcode()))
            .satisfies(e -> assertThat(e.getOrderNumber()).as("check orderNumber").isEqualTo(actual.getOrderNumber()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getExaminationDate()).as("check examinationDate").isEqualTo(actual.getExaminationDate()))
            .satisfies(e -> assertThat(e.getArchivedDate()).as("check archivedDate").isEqualTo(actual.getArchivedDate()))
            .satisfies(e -> assertThat(e.getArchivedReason()).as("check archivedReason").isEqualTo(actual.getArchivedReason()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveUpdatableRelationshipsEquals(Hive expected, Hive actual) {
        assertThat(expected)
            .as("Verify Hive relationships")
            .satisfies(e -> assertThat(e.getHiveType()).as("check hiveType").isEqualTo(actual.getHiveType()))
            .satisfies(e -> assertThat(e.getApiary()).as("check apiary").isEqualTo(actual.getApiary()));
    }
}
