package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HiveLocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveLocationAllPropertiesEquals(HiveLocation expected, HiveLocation actual) {
        assertHiveLocationAutoGeneratedPropertiesEquals(expected, actual);
        assertHiveLocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveLocationAllUpdatablePropertiesEquals(HiveLocation expected, HiveLocation actual) {
        assertHiveLocationUpdatableFieldsEquals(expected, actual);
        assertHiveLocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveLocationAutoGeneratedPropertiesEquals(HiveLocation expected, HiveLocation actual) {
        assertThat(expected)
            .as("Verify HiveLocation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveLocationUpdatableFieldsEquals(HiveLocation expected, HiveLocation actual) {
        assertThat(expected)
            .as("Verify HiveLocation relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHiveLocationUpdatableRelationshipsEquals(HiveLocation expected, HiveLocation actual) {
        // empty method
    }
}
