package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MovedHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovedHiveAllPropertiesEquals(MovedHive expected, MovedHive actual) {
        assertMovedHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertMovedHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovedHiveAllUpdatablePropertiesEquals(MovedHive expected, MovedHive actual) {
        assertMovedHiveUpdatableFieldsEquals(expected, actual);
        assertMovedHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovedHiveAutoGeneratedPropertiesEquals(MovedHive expected, MovedHive actual) {
        assertThat(expected)
            .as("Verify MovedHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovedHiveUpdatableFieldsEquals(MovedHive expected, MovedHive actual) {
        assertThat(expected)
            .as("Verify MovedHive relevant properties")
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovedHiveUpdatableRelationshipsEquals(MovedHive expected, MovedHive actual) {
        assertThat(expected)
            .as("Verify MovedHive relationships")
            .satisfies(e -> assertThat(e.getHarvestType()).as("check harvestType").isEqualTo(actual.getHarvestType()));
    }
}
