package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QueenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenAllPropertiesEquals(Queen expected, Queen actual) {
        assertQueenAutoGeneratedPropertiesEquals(expected, actual);
        assertQueenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenAllUpdatablePropertiesEquals(Queen expected, Queen actual) {
        assertQueenUpdatableFieldsEquals(expected, actual);
        assertQueenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenAutoGeneratedPropertiesEquals(Queen expected, Queen actual) {
        assertThat(expected)
            .as("Verify Queen auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenUpdatableFieldsEquals(Queen expected, Queen actual) {
        assertThat(expected)
            .as("Verify Queen relevant properties")
            .satisfies(e -> assertThat(e.getOrigin()).as("check origin").isEqualTo(actual.getOrigin()))
            .satisfies(e -> assertThat(e.getYear()).as("check year").isEqualTo(actual.getYear()))
            .satisfies(e -> assertThat(e.getIsMarked()).as("check isMarked").isEqualTo(actual.getIsMarked()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()))
            .satisfies(e -> assertThat(e.getActiveFromDate()).as("check activeFromDate").isEqualTo(actual.getActiveFromDate()))
            .satisfies(e -> assertThat(e.getActiveToDate()).as("check activeToDate").isEqualTo(actual.getActiveToDate()))
            .satisfies(e -> assertThat(e.getQueenChangeDate()).as("check queenChangeDate").isEqualTo(actual.getQueenChangeDate()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenUpdatableRelationshipsEquals(Queen expected, Queen actual) {
        assertThat(expected)
            .as("Verify Queen relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()));
    }
}
