package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QueenChangeHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenChangeHiveAllPropertiesEquals(QueenChangeHive expected, QueenChangeHive actual) {
        assertQueenChangeHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertQueenChangeHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenChangeHiveAllUpdatablePropertiesEquals(QueenChangeHive expected, QueenChangeHive actual) {
        assertQueenChangeHiveUpdatableFieldsEquals(expected, actual);
        assertQueenChangeHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenChangeHiveAutoGeneratedPropertiesEquals(QueenChangeHive expected, QueenChangeHive actual) {
        assertThat(expected)
            .as("Verify QueenChangeHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenChangeHiveUpdatableFieldsEquals(QueenChangeHive expected, QueenChangeHive actual) {
        assertThat(expected)
            .as("Verify QueenChangeHive relevant properties")
            .satisfies(e -> assertThat(e.getDateQueenChange()).as("check dateQueenChange").isEqualTo(actual.getDateQueenChange()))
            .satisfies(e -> assertThat(e.getReminderId()).as("check reminderId").isEqualTo(actual.getReminderId()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQueenChangeHiveUpdatableRelationshipsEquals(QueenChangeHive expected, QueenChangeHive actual) {
        // empty method
    }
}
