package rs.hexatech.beeback.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReproductionHiveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReproductionHiveAllPropertiesEquals(ReproductionHive expected, ReproductionHive actual) {
        assertReproductionHiveAutoGeneratedPropertiesEquals(expected, actual);
        assertReproductionHiveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReproductionHiveAllUpdatablePropertiesEquals(ReproductionHive expected, ReproductionHive actual) {
        assertReproductionHiveUpdatableFieldsEquals(expected, actual);
        assertReproductionHiveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReproductionHiveAutoGeneratedPropertiesEquals(ReproductionHive expected, ReproductionHive actual) {
        assertThat(expected)
            .as("Verify ReproductionHive auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReproductionHiveUpdatableFieldsEquals(ReproductionHive expected, ReproductionHive actual) {
        assertThat(expected)
            .as("Verify ReproductionHive relevant properties")
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()))
            .satisfies(e -> assertThat(e.getExternalId()).as("check externalId").isEqualTo(actual.getExternalId()))
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getDateCreated()).as("check dateCreated").isEqualTo(actual.getDateCreated()))
            .satisfies(e -> assertThat(e.getDateModified()).as("check dateModified").isEqualTo(actual.getDateModified()))
            .satisfies(e -> assertThat(e.getDateSynched()).as("check dateSynched").isEqualTo(actual.getDateSynched()))
            .satisfies(e -> assertThat(e.getDateDeleted()).as("check dateDeleted").isEqualTo(actual.getDateDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReproductionHiveUpdatableRelationshipsEquals(ReproductionHive expected, ReproductionHive actual) {
        assertThat(expected)
            .as("Verify ReproductionHive relationships")
            .satisfies(e -> assertThat(e.getHive()).as("check hive").isEqualTo(actual.getHive()));
    }
}
